# perfectUnityPlugin configuration

homes:
  max-homes: -1 # -1 = unlimited, or set a number to limit
  gui:
    gui-size: 54 # size of the GUI (Must be divisible by 9)
    pagination:
      items-per-page: 45

