name: perfectUnityPlugin
version: 1.3.2
main: com.anon.perfectUnityPlugin.perfectUnityPlugin
api-version: 1.20
commands:
  sethome:
    description: Set a new Home
    usage: /sethome <name> [overwrite]
  home:
    description: Open the Home Manager GUI or Teleport to a Home using the [name]
    usage: /home [name]
  heads:
    description: opens the heads gui or gives heads
    usage: /heads [name] [amount]
  cchead:
    description: Create a Custom Head
    usage: /cchead <name> <base64> [name-color]
permissions:
  perfectUnityPlugin.use:
    default: true